### ISSUE TITLE
How do you whitelist domains instead of IPs?

### ISSUE THREAD

**Issue by bionicles** [ibm-cloud-docs/ComposeForPostgreSQL#2]
Hi,

Thanks for making Compose

To make sure only API can access DB and prevent DDOS in Serverless apps, I want to whitelist a domain instead of an API, and limit connections to HTTPS only

We want to host our app with Zeit Now and the IPs are not fixed so we can’t whitelist based on IP (I think... please
ask around and holler if I’m wrong)

Basically just want to put 

https://www.example.com/api 

In the whitelist. How do you make something like this work with Compose PostgreSQL?

Thanks in advance for your insight,

Bion

**Comment by acdntlpoet** [comment]
Apologies for the delay in reply on this issue. Currently allowlisting only support IPs or IP ranges. For further discussion on how to accurately achieve your goals, please open a [support case](https://cloud.ibm.com/unifiedsupport/cases/add) with details as above to allow our support team to address your concerns.
